package src

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/devfacet/gocmd/v3"
	"github.com/google/go-github/v47/github"
)

const (
	fncInit            = "Init"
	fncReplace         = "Replace"
	fncMerge           = "Merge"
	gitOwner           = "github"
	gitRepo            = "gitignore"
	gitignoreFileMode  = 0644
	requestTimeout     = 15 * time.Second
	maxRequestAttempts = 3
	generatedHeader    = "# Generated by ignoreinit (https://github.com/loupeznik/ignoreinit)\n\n"
)

var retryDelay = 200 * time.Millisecond

type gitignoreClient interface {
	ListTemplates(ctx context.Context) ([]string, error)
	DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error)
}

type githubGitignoreClient struct {
	client *github.Client
}

func InitHandlers() {
	gocmd.HandleFlag(fncInit, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncInit)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if exists {
			fmt.Printf(".gitignore already exists in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, true, false)

		if err != nil {
			return err
		}

		fmt.Printf("Created .gitignore in %s\n", location)

		return nil
	})

	gocmd.HandleFlag(fncReplace, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncReplace)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if !exists {
			fmt.Printf(".gitignore does not exist in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, false, false)

		if err != nil {
			return err
		}

		fmt.Printf("Replaced .gitignore in %s\n", location)

		return nil
	})

	gocmd.HandleFlag(fncMerge, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncMerge)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if !exists {
			fmt.Printf(".gitignore does not exist in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, false, true)

		if err != nil {
			return err
		}

		fmt.Printf("Merged .gitignore in %s\n", location)

		return nil
	})
}

func handleParams(params []string) (string, string, error) {
	if len(params) == 0 {
		return "", "", errors.New("no arguments supplied")
	}

	if len(params) == 1 {
		params = append(params, ".")
	}

	return params[0], params[1], nil
}

func getIgnore(language string, location string, isNew bool, isMerge bool) error {
	client := githubGitignoreClient{client: github.NewClient(nil)}
	bytes, err := fetchIgnore(language, client)

	if err != nil {
		return err
	}

	return writeIgnore(filepath.Join(location, ".gitignore"), bytes, isNew, isMerge)
}

func gitignoreExists(gitignorePath string) (bool, error) {
	_, err := os.Stat(gitignorePath)
	if err == nil {
		return true, nil
	}

	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}

	return false, fmt.Errorf("could not inspect %s: %w", gitignorePath, err)
}

func fetchIgnore(language string, client gitignoreClient) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
	defer cancel()

	var templates []string
	if err := withRetry(ctx, func() error {
		var err error
		templates, err = client.ListTemplates(ctx)
		return err
	}); err != nil {
		return nil, fmt.Errorf("could not list gitignore templates from %s/%s: %w", gitOwner, gitRepo, err)
	}

	templatePath := findTemplate(language, templates)
	if templatePath == "" {
		return nil, fmt.Errorf("could not find .gitignore template for %q; check the language name against github.com/github/gitignore", language)
	}

	var content []byte
	if err := withRetry(ctx, func() error {
		var err error
		content, err = client.DownloadTemplate(ctx, templatePath)
		return err
	}); err != nil {
		return nil, fmt.Errorf("could not download .gitignore template for %q from %s/%s: %w", language, gitOwner, gitRepo, err)
	}

	return content, nil
}

func withRetry(ctx context.Context, operation func() error) error {
	var lastErr error

	for attempt := 1; attempt <= maxRequestAttempts; attempt++ {
		if err := operation(); err != nil {
			lastErr = err
		} else {
			return nil
		}

		if attempt == maxRequestAttempts {
			break
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(retryDelay):
		}
	}

	return lastErr
}

func findTemplate(language string, templates []string) string {
	for _, template := range templates {
		name := strings.TrimSuffix(filepath.Base(template), filepath.Ext(template))
		if strings.EqualFold(name, language) {
			return template
		}
	}

	return ""
}

func writeIgnore(gitignorePath string, content []byte, isNew bool, isMerge bool) error {
	if isMerge {
		existing, err := os.ReadFile(gitignorePath)
		if err != nil {
			return fmt.Errorf("could not read existing %s before merge: %w", gitignorePath, err)
		}

		content = mergeIgnore(existing, content)
	} else if isNew {
		content = append([]byte(generatedHeader), content...)
	}

	if err := os.WriteFile(gitignorePath, content, gitignoreFileMode); err != nil {
		return fmt.Errorf("could not write %s: %w", gitignorePath, err)
	}

	return nil
}

func mergeIgnore(existing []byte, content []byte) []byte {
	merged := append([]byte{}, existing...)

	if len(bytes.TrimSpace(merged)) > 0 {
		merged = bytes.TrimRight(merged, "\n")
		merged = append(merged, '\n', '\n')
	}

	return append(merged, content...)
}

func (c githubGitignoreClient) ListTemplates(ctx context.Context) ([]string, error) {
	_, directoryContent, _, err := c.client.Repositories.GetContents(ctx, gitOwner, gitRepo, "/", &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}

	templates := make([]string, 0, len(directoryContent))
	for _, file := range directoryContent {
		if file == nil || file.Name == nil || file.Path == nil || !strings.HasSuffix(*file.Name, ".gitignore") {
			continue
		}

		templates = append(templates, file.GetPath())
	}

	return templates, nil
}

func (c githubGitignoreClient) DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error) {
	reader, response, err := c.client.Repositories.DownloadContents(ctx, gitOwner, gitRepo, templatePath, &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}

	if response == nil || response.Response == nil || response.StatusCode != 200 {
		status := "unknown status"
		if response != nil && response.Response != nil {
			status = response.Status
		}

		return nil, fmt.Errorf("unexpected GitHub response: %s", status)
	}

	defer reader.Close()

	content, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}

	return content, nil
}
