package src

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/devfacet/gocmd/v3"
	"github.com/google/go-github/v47/github"
)

const (
	fncInit            = "Init"
	fncReplace         = "Replace"
	fncMerge           = "Merge"
	fncList            = "List"
	fncSearch          = "Search"
	fncCompletion      = "Completion"
	gitOwner           = "github"
	gitRepo            = "gitignore"
	gitignoreFileMode  = 0644
	requestTimeout     = 15 * time.Second
	maxRequestAttempts = 3
	generatedHeader    = "# Generated by ignoreinit (https://github.com/loupeznik/ignoreinit)\n\n"
	sectionStartFormat = "# >>> ignoreinit: %s\n"
	sectionEndFormat   = "# <<< ignoreinit: %s\n"
)

var retryDelay = 200 * time.Millisecond

type gitignoreClient interface {
	ListTemplates(ctx context.Context) ([]string, error)
	DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error)
}

type githubGitignoreClient struct {
	client *github.Client
}

func InitHandlers() {
	gocmd.HandleFlag(fncList, func(cmd *gocmd.Cmd, args []string) error {
		templates, err := listTemplateNames(githubGitignoreClient{client: github.NewClient(nil)})
		if err != nil {
			return err
		}

		fmt.Println(strings.Join(templates, "\n"))
		return nil
	})

	gocmd.HandleFlag(fncSearch, func(cmd *gocmd.Cmd, args []string) error {
		params := cmd.FlagArgs(fncSearch)[1:]
		if len(params) == 0 {
			return errors.New("no search term supplied")
		}

		matches, err := searchTemplateNames(params[0], githubGitignoreClient{client: github.NewClient(nil)})
		if err != nil {
			return err
		}
		if len(matches) == 0 {
			return fmt.Errorf("no .gitignore templates matched %q", params[0])
		}

		fmt.Println(strings.Join(matches, "\n"))
		return nil
	})

	gocmd.HandleFlag(fncCompletion, func(cmd *gocmd.Cmd, args []string) error {
		params := cmd.FlagArgs(fncCompletion)[1:]
		if len(params) == 0 {
			return errors.New("no shell supplied")
		}

		completion, err := generateCompletion(params[0])
		if err != nil {
			return err
		}

		fmt.Print(completion)
		return nil
	})

	gocmd.HandleFlag(fncInit, func(cmd *gocmd.Cmd, args []string) error {
		templates, location, err := handleGenerationParams(cmd.FlagArgs(fncInit)[1:])
		shouldPrint := cmd.FlagValue(fncInit+".Print") == true

		if err != nil {
			return err
		}

		if !shouldPrint {
			gitignorePath := filepath.Join(location, ".gitignore")
			if exists, err := gitignoreExists(gitignorePath); err != nil {
				return err
			} else if exists {
				fmt.Printf(".gitignore already exists in %s\n", location)
				return nil
			}
		}

		err = getIgnore(templates, location, true, false, shouldPrint)

		if err != nil {
			return err
		}

		if !shouldPrint {
			fmt.Printf("Created .gitignore in %s\n", location)
		}

		return nil
	})

	gocmd.HandleFlag(fncReplace, func(cmd *gocmd.Cmd, args []string) error {
		templates, location, err := handleGenerationParams(cmd.FlagArgs(fncReplace)[1:])
		shouldPrint := cmd.FlagValue(fncReplace+".Print") == true

		if err != nil {
			return err
		}

		if !shouldPrint {
			gitignorePath := filepath.Join(location, ".gitignore")
			if exists, err := gitignoreExists(gitignorePath); err != nil {
				return err
			} else if !exists {
				fmt.Printf(".gitignore does not exist in %s\n", location)
				return nil
			}
		}

		err = getIgnore(templates, location, false, false, shouldPrint)

		if err != nil {
			return err
		}

		if !shouldPrint {
			fmt.Printf("Replaced .gitignore in %s\n", location)
		}

		return nil
	})

	gocmd.HandleFlag(fncMerge, func(cmd *gocmd.Cmd, args []string) error {
		templates, location, err := handleGenerationParams(cmd.FlagArgs(fncMerge)[1:])
		shouldPrint := cmd.FlagValue(fncMerge+".Print") == true

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if !exists {
			fmt.Printf(".gitignore does not exist in %s\n", location)
			return nil
		}

		err = getIgnore(templates, location, false, true, shouldPrint)

		if err != nil {
			return err
		}

		if !shouldPrint {
			fmt.Printf("Merged .gitignore in %s\n", location)
		}

		return nil
	})
}

func handleParams(params []string) (string, string, error) {
	templates, location, err := handleGenerationParams(params)
	if err != nil {
		return "", "", err
	}

	return templates[0], location, nil
}

func handleGenerationParams(params []string) ([]string, string, error) {
	if len(params) == 0 {
		return nil, "", errors.New("no arguments supplied")
	}

	if len(params) == 1 {
		return []string{params[0]}, ".", nil
	}

	lastParam := params[len(params)-1]
	if looksLikeLocation(lastParam) {
		return params[:len(params)-1], lastParam, nil
	}

	return params, ".", nil
}

func looksLikeLocation(value string) bool {
	if value == "." || value == ".." || strings.HasPrefix(value, "./") || strings.HasPrefix(value, "../") || strings.HasPrefix(value, "~") || filepath.IsAbs(value) {
		return true
	}

	if strings.ContainsAny(value, `/\`) || filepath.VolumeName(value) != "" {
		return true
	}

	info, err := os.Stat(value)
	return err == nil && info.IsDir()
}

func getIgnore(templates []string, location string, isNew bool, isMerge bool, shouldPrint bool) error {
	client := githubGitignoreClient{client: github.NewClient(nil)}
	content, err := fetchIgnores(templates, client)

	if err != nil {
		return err
	}

	return writeIgnore(filepath.Join(location, ".gitignore"), content, isNew, isMerge, shouldPrint)
}

func gitignoreExists(gitignorePath string) (bool, error) {
	_, err := os.Stat(gitignorePath)
	if err == nil {
		return true, nil
	}

	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}

	return false, fmt.Errorf("could not inspect %s: %w", gitignorePath, err)
}

func fetchIgnore(language string, client gitignoreClient) ([]byte, error) {
	return fetchIgnores([]string{language}, client)
}

func fetchIgnores(languages []string, client gitignoreClient) ([]byte, error) {
	templates, err := listTemplates(client)
	if err != nil {
		return nil, err
	}

	contents := make([][]byte, 0, len(languages))
	for _, language := range languages {
		templatePath := findTemplate(language, templates)
		if templatePath == "" {
			return nil, fmt.Errorf("could not find .gitignore template for %q; check the language name against github.com/github/gitignore", language)
		}

		var content []byte
		if err := withRetryTimeout(func(ctx context.Context) error {
			var err error
			content, err = client.DownloadTemplate(ctx, templatePath)
			return err
		}); err != nil {
			return nil, fmt.Errorf("could not download .gitignore template for %q from %s/%s: %w", language, gitOwner, gitRepo, err)
		}

		contents = append(contents, renderTemplateSection(templateName(templatePath), content))
	}

	return joinContent(contents), nil
}

func renderTemplateSection(name string, content []byte) []byte {
	content = bytes.TrimRight(content, "\r\n")
	if len(bytes.TrimSpace(content)) == 0 {
		return nil
	}

	var section []byte
	section = append(section, []byte(fmt.Sprintf(sectionStartFormat, name))...)
	section = append(section, content...)
	section = append(section, '\n')
	section = append(section, []byte(fmt.Sprintf(sectionEndFormat, name))...)

	return section
}

func joinContent(contents [][]byte) []byte {
	var joined []byte
	for _, content := range contents {
		content = bytes.TrimRight(content, "\r\n")
		if len(bytes.TrimSpace(content)) == 0 {
			continue
		}

		if len(joined) > 0 {
			joined = append(joined, '\n', '\n')
		}
		joined = append(joined, content...)
	}
	if len(joined) > 0 {
		joined = append(joined, '\n')
	}

	return joined
}

func listTemplateNames(client gitignoreClient) ([]string, error) {
	templates, err := listTemplates(client)
	if err != nil {
		return nil, err
	}

	names := make([]string, 0, len(templates))
	for _, template := range templates {
		names = append(names, templateName(template))
	}
	sort.Strings(names)

	return names, nil
}

func listTemplates(client gitignoreClient) ([]string, error) {
	var templates []string
	if err := withRetryTimeout(func(ctx context.Context) error {
		var err error
		templates, err = client.ListTemplates(ctx)
		return err
	}); err != nil {
		return nil, fmt.Errorf("could not list gitignore templates from %s/%s: %w", gitOwner, gitRepo, err)
	}

	return templates, nil
}

func searchTemplateNames(term string, client gitignoreClient) ([]string, error) {
	names, err := listTemplateNames(client)
	if err != nil {
		return nil, err
	}

	return searchNames(term, names), nil
}

func searchNames(term string, names []string) []string {
	term = strings.TrimSpace(term)
	if term == "" {
		return nil
	}

	matches := make([]templateMatch, 0, len(names))
	for _, name := range names {
		if score, ok := templateMatchScore(term, name); ok {
			matches = append(matches, templateMatch{name: name, score: score})
		}
	}

	sort.SliceStable(matches, func(i int, j int) bool {
		if matches[i].score == matches[j].score {
			return matches[i].name < matches[j].name
		}

		return matches[i].score < matches[j].score
	})

	results := make([]string, 0, len(matches))
	for _, match := range matches {
		results = append(results, match.name)
	}

	return results
}

type templateMatch struct {
	name  string
	score int
}

func templateMatchScore(term string, name string) (int, bool) {
	normalizedTerm := normalizeTemplateName(term)
	normalizedName := normalizeTemplateName(name)

	switch {
	case normalizedTerm == normalizedName:
		return 0, true
	case strings.HasPrefix(normalizedName, normalizedTerm):
		return 10 + len(normalizedName) - len(normalizedTerm), true
	case strings.Contains(normalizedName, normalizedTerm):
		return 100 + strings.Index(normalizedName, normalizedTerm), true
	}

	if score, ok := subsequenceScore(normalizedTerm, normalizedName); ok {
		return 200 + score, true
	}

	distance := editDistance(normalizedTerm, normalizedName)
	if distance <= maxEditDistance(normalizedTerm) {
		return 300 + distance, true
	}

	return 0, false
}

func normalizeTemplateName(value string) string {
	return strings.ToLower(strings.ReplaceAll(strings.TrimSpace(value), " ", ""))
}

func subsequenceScore(term string, name string) (int, bool) {
	if term == "" {
		return 0, false
	}

	position := 0
	score := 0
	for _, char := range term {
		index := strings.IndexRune(name[position:], char)
		if index == -1 {
			return 0, false
		}

		score += index
		position += index + 1
	}

	return score + len(name) - len(term), true
}

func maxEditDistance(term string) int {
	if len(term) <= 4 {
		return 1
	}

	return len(term) / 3
}

func editDistance(left string, right string) int {
	previous := make([]int, len(right)+1)
	for index := range previous {
		previous[index] = index
	}

	for leftIndex := 1; leftIndex <= len(left); leftIndex++ {
		current := make([]int, len(right)+1)
		current[0] = leftIndex

		for rightIndex := 1; rightIndex <= len(right); rightIndex++ {
			cost := 0
			if left[leftIndex-1] != right[rightIndex-1] {
				cost = 1
			}

			current[rightIndex] = minInt(
				current[rightIndex-1]+1,
				previous[rightIndex]+1,
				previous[rightIndex-1]+cost,
			)
		}

		previous = current
	}

	return previous[len(right)]
}

func minInt(values ...int) int {
	minimum := values[0]
	for _, value := range values[1:] {
		if value < minimum {
			minimum = value
		}
	}

	return minimum
}

func generateCompletion(shell string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(shell)) {
	case "bash":
		return bashCompletion(), nil
	case "zsh":
		return zshCompletion(), nil
	case "fish":
		return fishCompletion(), nil
	case "powershell", "pwsh":
		return powershellCompletion(), nil
	default:
		return "", fmt.Errorf("unsupported shell %q; supported shells: bash, zsh, fish, powershell", shell)
	}
}

func bashCompletion() string {
	return `_ignoreinit_completion() {
  local current previous commands shells
  COMPREPLY=()
  current="${COMP_WORDS[COMP_CWORD]}"
  previous="${COMP_WORDS[COMP_CWORD-1]}"
  commands="init replace merge list search completion"
  shells="bash zsh fish powershell"

  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${commands}" -- "${current}") )
    return 0
  fi

  if [[ ${COMP_WORDS[1]} == "completion" && ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "${shells}" -- "${current}") )
    return 0
  fi

  case "${previous}" in
    init|replace|merge)
      COMPREPLY=( $(compgen -W "--print -p" -- "${current}") )
      ;;
  esac
}

complete -F _ignoreinit_completion ignoreinit
`
}

func zshCompletion() string {
	return `#compdef ignoreinit

_ignoreinit() {
  local -a commands shells generation_flags
  commands=(
    'init:initialize .gitignore'
    'replace:replace current .gitignore'
    'merge:merge templates into current .gitignore'
    'list:list available templates'
    'search:search available templates'
    'completion:generate shell completion'
  )
  shells=(bash zsh fish powershell)
  generation_flags=('--print[print generated content to stdout]' '-p[print generated content to stdout]')

  if (( CURRENT == 2 )); then
    _describe 'commands' commands
    return
  fi

  case "$words[2]" in
    completion)
      _describe 'shells' shells
      ;;
    init|replace|merge)
      _describe 'options' generation_flags
      ;;
  esac
}

compdef _ignoreinit ignoreinit
`
}

func fishCompletion() string {
	return `complete -c ignoreinit -f
complete -c ignoreinit -n "__fish_use_subcommand" -a "init" -d "Initialize .gitignore"
complete -c ignoreinit -n "__fish_use_subcommand" -a "replace" -d "Replace current .gitignore"
complete -c ignoreinit -n "__fish_use_subcommand" -a "merge" -d "Merge templates into current .gitignore"
complete -c ignoreinit -n "__fish_use_subcommand" -a "list" -d "List available templates"
complete -c ignoreinit -n "__fish_use_subcommand" -a "search" -d "Search available templates"
complete -c ignoreinit -n "__fish_use_subcommand" -a "completion" -d "Generate shell completion"
complete -c ignoreinit -n "__fish_seen_subcommand_from init replace merge" -s p -l print -d "Print generated content to stdout"
complete -c ignoreinit -n "__fish_seen_subcommand_from completion" -a "bash zsh fish powershell"
`
}

func powershellCompletion() string {
	return `Register-ArgumentCompleter -Native -CommandName ignoreinit -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $commands = @("init", "replace", "merge", "list", "search", "completion")
  $shells = @("bash", "zsh", "fish", "powershell")
  $words = $commandAst.CommandElements | ForEach-Object { $_.Extent.Text }

  if ($words.Count -le 2) {
    $commands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_)
    }
    return
  }

  if ($words[1] -eq "completion") {
    $shells | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_)
    }
    return
  }

  if ($words[1] -in @("init", "replace", "merge")) {
    @("--print", "-p") | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterName", $_)
    }
  }
}
`
}

func withRetryTimeout(operation func(context.Context) error) error {
	ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
	defer cancel()

	return withRetry(ctx, func() error {
		return operation(ctx)
	})
}

func withRetry(ctx context.Context, operation func() error) error {
	var lastErr error

	for attempt := 1; attempt <= maxRequestAttempts; attempt++ {
		if err := operation(); err != nil {
			lastErr = err
		} else {
			return nil
		}

		if attempt == maxRequestAttempts {
			break
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(retryDelay):
		}
	}

	return lastErr
}

func findTemplate(language string, templates []string) string {
	for _, template := range templates {
		if strings.EqualFold(templateName(template), language) {
			return template
		}
	}

	return ""
}

func templateName(template string) string {
	return strings.TrimSuffix(filepath.Base(template), filepath.Ext(template))
}

func writeIgnore(gitignorePath string, content []byte, isNew bool, isMerge bool, shouldPrint bool) error {
	if isMerge {
		existing, err := os.ReadFile(gitignorePath)
		if err != nil {
			return fmt.Errorf("could not read existing %s before merge: %w", gitignorePath, err)
		}

		content = mergeIgnore(existing, content)
	} else if isNew {
		content = append([]byte(generatedHeader), content...)
	}

	if shouldPrint {
		_, err := os.Stdout.Write(content)
		return err
	}

	if err := os.WriteFile(gitignorePath, content, gitignoreFileMode); err != nil {
		return fmt.Errorf("could not write %s: %w", gitignorePath, err)
	}

	return nil
}

func mergeIgnore(existing []byte, content []byte) []byte {
	return dedupeIgnoreContent(joinContent([][]byte{existing, content}))
}

func dedupeIgnoreContent(content []byte) []byte {
	lines := strings.Split(strings.ReplaceAll(string(content), "\r\n", "\n"), "\n")
	seen := map[string]struct{}{}
	deduped := make([]string, 0, len(lines))
	previousBlank := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if len(deduped) > 0 && !previousBlank {
				deduped = append(deduped, "")
				previousBlank = true
			}
			continue
		}

		if shouldDedupeLine(trimmed) {
			if _, exists := seen[trimmed]; exists {
				continue
			}
			seen[trimmed] = struct{}{}
		}

		deduped = append(deduped, line)
		previousBlank = false
	}

	for len(deduped) > 0 && deduped[len(deduped)-1] == "" {
		deduped = deduped[:len(deduped)-1]
	}

	if len(deduped) == 0 {
		return nil
	}

	return []byte(strings.Join(deduped, "\n") + "\n")
}

func shouldDedupeLine(trimmed string) bool {
	return !strings.HasPrefix(trimmed, "#")
}

func (c githubGitignoreClient) ListTemplates(ctx context.Context) ([]string, error) {
	_, directoryContent, _, err := c.client.Repositories.GetContents(ctx, gitOwner, gitRepo, "/", &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}

	templates := make([]string, 0, len(directoryContent))
	for _, file := range directoryContent {
		if file == nil || file.Name == nil || file.Path == nil || !strings.HasSuffix(*file.Name, ".gitignore") {
			continue
		}

		templates = append(templates, file.GetPath())
	}

	return templates, nil
}

func (c githubGitignoreClient) DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error) {
	reader, response, err := c.client.Repositories.DownloadContents(ctx, gitOwner, gitRepo, templatePath, &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}
	if reader != nil {
		defer reader.Close()
	}

	if response == nil || response.Response == nil || response.StatusCode != 200 {
		status := "unknown status"
		if response != nil && response.Response != nil {
			status = response.Status
		}

		return nil, fmt.Errorf("unexpected GitHub response: %s", status)
	}

	content, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}

	return content, nil
}
