package src

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/devfacet/gocmd/v3"
	"github.com/google/go-github/v47/github"
)

const (
	fncInit            = "Init"
	fncReplace         = "Replace"
	fncMerge           = "Merge"
	fncList            = "List"
	fncSearch          = "Search"
	gitOwner           = "github"
	gitRepo            = "gitignore"
	gitignoreFileMode  = 0644
	requestTimeout     = 15 * time.Second
	maxRequestAttempts = 3
	generatedHeader    = "# Generated by ignoreinit (https://github.com/loupeznik/ignoreinit)\n\n"
)

var retryDelay = 200 * time.Millisecond

type gitignoreClient interface {
	ListTemplates(ctx context.Context) ([]string, error)
	DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error)
}

type githubGitignoreClient struct {
	client *github.Client
}

func InitHandlers() {
	gocmd.HandleFlag(fncList, func(cmd *gocmd.Cmd, args []string) error {
		templates, err := listTemplateNames(githubGitignoreClient{client: github.NewClient(nil)})
		if err != nil {
			return err
		}

		fmt.Println(strings.Join(templates, "\n"))
		return nil
	})

	gocmd.HandleFlag(fncSearch, func(cmd *gocmd.Cmd, args []string) error {
		params := cmd.FlagArgs(fncSearch)[1:]
		if len(params) == 0 {
			return errors.New("no search term supplied")
		}

		matches, err := searchTemplateNames(params[0], githubGitignoreClient{client: github.NewClient(nil)})
		if err != nil {
			return err
		}
		if len(matches) == 0 {
			return fmt.Errorf("no .gitignore templates matched %q", params[0])
		}

		fmt.Println(strings.Join(matches, "\n"))
		return nil
	})

	gocmd.HandleFlag(fncInit, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncInit)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if exists {
			fmt.Printf(".gitignore already exists in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, true, false)

		if err != nil {
			return err
		}

		fmt.Printf("Created .gitignore in %s\n", location)

		return nil
	})

	gocmd.HandleFlag(fncReplace, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncReplace)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if !exists {
			fmt.Printf(".gitignore does not exist in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, false, false)

		if err != nil {
			return err
		}

		fmt.Printf("Replaced .gitignore in %s\n", location)

		return nil
	})

	gocmd.HandleFlag(fncMerge, func(cmd *gocmd.Cmd, args []string) error {
		language, location, err := handleParams(cmd.FlagArgs(fncMerge)[1:])

		if err != nil {
			return err
		}

		gitignorePath := filepath.Join(location, ".gitignore")
		if exists, err := gitignoreExists(gitignorePath); err != nil {
			return err
		} else if !exists {
			fmt.Printf(".gitignore does not exist in %s\n", location)
			return nil
		}

		err = getIgnore(language, location, false, true)

		if err != nil {
			return err
		}

		fmt.Printf("Merged .gitignore in %s\n", location)

		return nil
	})
}

func handleParams(params []string) (string, string, error) {
	if len(params) == 0 {
		return "", "", errors.New("no arguments supplied")
	}

	if len(params) == 1 {
		params = append(params, ".")
	}

	return params[0], params[1], nil
}

func getIgnore(language string, location string, isNew bool, isMerge bool) error {
	client := githubGitignoreClient{client: github.NewClient(nil)}
	content, err := fetchIgnore(language, client)

	if err != nil {
		return err
	}

	return writeIgnore(filepath.Join(location, ".gitignore"), content, isNew, isMerge)
}

func gitignoreExists(gitignorePath string) (bool, error) {
	_, err := os.Stat(gitignorePath)
	if err == nil {
		return true, nil
	}

	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}

	return false, fmt.Errorf("could not inspect %s: %w", gitignorePath, err)
}

func fetchIgnore(language string, client gitignoreClient) ([]byte, error) {
	templates, err := listTemplates(client)
	if err != nil {
		return nil, err
	}

	templatePath := findTemplate(language, templates)
	if templatePath == "" {
		return nil, fmt.Errorf("could not find .gitignore template for %q; check the language name against github.com/github/gitignore", language)
	}

	var content []byte
	if err := withRetryTimeout(func(ctx context.Context) error {
		var err error
		content, err = client.DownloadTemplate(ctx, templatePath)
		return err
	}); err != nil {
		return nil, fmt.Errorf("could not download .gitignore template for %q from %s/%s: %w", language, gitOwner, gitRepo, err)
	}

	return content, nil
}

func listTemplateNames(client gitignoreClient) ([]string, error) {
	templates, err := listTemplates(client)
	if err != nil {
		return nil, err
	}

	names := make([]string, 0, len(templates))
	for _, template := range templates {
		names = append(names, templateName(template))
	}
	sort.Strings(names)

	return names, nil
}

func listTemplates(client gitignoreClient) ([]string, error) {
	var templates []string
	if err := withRetryTimeout(func(ctx context.Context) error {
		var err error
		templates, err = client.ListTemplates(ctx)
		return err
	}); err != nil {
		return nil, fmt.Errorf("could not list gitignore templates from %s/%s: %w", gitOwner, gitRepo, err)
	}

	return templates, nil
}

func searchTemplateNames(term string, client gitignoreClient) ([]string, error) {
	names, err := listTemplateNames(client)
	if err != nil {
		return nil, err
	}

	return searchNames(term, names), nil
}

func searchNames(term string, names []string) []string {
	term = strings.TrimSpace(term)
	if term == "" {
		return nil
	}

	matches := make([]templateMatch, 0, len(names))
	for _, name := range names {
		if score, ok := templateMatchScore(term, name); ok {
			matches = append(matches, templateMatch{name: name, score: score})
		}
	}

	sort.SliceStable(matches, func(i int, j int) bool {
		if matches[i].score == matches[j].score {
			return matches[i].name < matches[j].name
		}

		return matches[i].score < matches[j].score
	})

	results := make([]string, 0, len(matches))
	for _, match := range matches {
		results = append(results, match.name)
	}

	return results
}

type templateMatch struct {
	name  string
	score int
}

func templateMatchScore(term string, name string) (int, bool) {
	normalizedTerm := normalizeTemplateName(term)
	normalizedName := normalizeTemplateName(name)

	switch {
	case normalizedTerm == normalizedName:
		return 0, true
	case strings.HasPrefix(normalizedName, normalizedTerm):
		return 10 + len(normalizedName) - len(normalizedTerm), true
	case strings.Contains(normalizedName, normalizedTerm):
		return 100 + strings.Index(normalizedName, normalizedTerm), true
	}

	if score, ok := subsequenceScore(normalizedTerm, normalizedName); ok {
		return 200 + score, true
	}

	distance := editDistance(normalizedTerm, normalizedName)
	if distance <= maxEditDistance(normalizedTerm) {
		return 300 + distance, true
	}

	return 0, false
}

func normalizeTemplateName(value string) string {
	return strings.ToLower(strings.ReplaceAll(strings.TrimSpace(value), " ", ""))
}

func subsequenceScore(term string, name string) (int, bool) {
	if term == "" {
		return 0, false
	}

	position := 0
	score := 0
	for _, char := range term {
		index := strings.IndexRune(name[position:], char)
		if index == -1 {
			return 0, false
		}

		score += index
		position += index + 1
	}

	return score + len(name) - len(term), true
}

func maxEditDistance(term string) int {
	if len(term) <= 4 {
		return 1
	}

	return len(term) / 3
}

func editDistance(left string, right string) int {
	previous := make([]int, len(right)+1)
	for index := range previous {
		previous[index] = index
	}

	for leftIndex := 1; leftIndex <= len(left); leftIndex++ {
		current := make([]int, len(right)+1)
		current[0] = leftIndex

		for rightIndex := 1; rightIndex <= len(right); rightIndex++ {
			cost := 0
			if left[leftIndex-1] != right[rightIndex-1] {
				cost = 1
			}

			current[rightIndex] = minInt(
				current[rightIndex-1]+1,
				previous[rightIndex]+1,
				previous[rightIndex-1]+cost,
			)
		}

		previous = current
	}

	return previous[len(right)]
}

func minInt(values ...int) int {
	minimum := values[0]
	for _, value := range values[1:] {
		if value < minimum {
			minimum = value
		}
	}

	return minimum
}

func withRetryTimeout(operation func(context.Context) error) error {
	ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
	defer cancel()

	return withRetry(ctx, func() error {
		return operation(ctx)
	})
}

func withRetry(ctx context.Context, operation func() error) error {
	var lastErr error

	for attempt := 1; attempt <= maxRequestAttempts; attempt++ {
		if err := operation(); err != nil {
			lastErr = err
		} else {
			return nil
		}

		if attempt == maxRequestAttempts {
			break
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(retryDelay):
		}
	}

	return lastErr
}

func findTemplate(language string, templates []string) string {
	for _, template := range templates {
		if strings.EqualFold(templateName(template), language) {
			return template
		}
	}

	return ""
}

func templateName(template string) string {
	return strings.TrimSuffix(filepath.Base(template), filepath.Ext(template))
}

func writeIgnore(gitignorePath string, content []byte, isNew bool, isMerge bool) error {
	if isMerge {
		existing, err := os.ReadFile(gitignorePath)
		if err != nil {
			return fmt.Errorf("could not read existing %s before merge: %w", gitignorePath, err)
		}

		content = mergeIgnore(existing, content)
	} else if isNew {
		content = append([]byte(generatedHeader), content...)
	}

	if err := os.WriteFile(gitignorePath, content, gitignoreFileMode); err != nil {
		return fmt.Errorf("could not write %s: %w", gitignorePath, err)
	}

	return nil
}

func mergeIgnore(existing []byte, content []byte) []byte {
	merged := append([]byte{}, existing...)

	if len(bytes.TrimSpace(merged)) > 0 {
		merged = bytes.TrimRight(merged, "\r\n")
		merged = append(merged, '\n', '\n')
	}

	return append(merged, content...)
}

func (c githubGitignoreClient) ListTemplates(ctx context.Context) ([]string, error) {
	_, directoryContent, _, err := c.client.Repositories.GetContents(ctx, gitOwner, gitRepo, "/", &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}

	templates := make([]string, 0, len(directoryContent))
	for _, file := range directoryContent {
		if file == nil || file.Name == nil || file.Path == nil || !strings.HasSuffix(*file.Name, ".gitignore") {
			continue
		}

		templates = append(templates, file.GetPath())
	}

	return templates, nil
}

func (c githubGitignoreClient) DownloadTemplate(ctx context.Context, templatePath string) ([]byte, error) {
	reader, response, err := c.client.Repositories.DownloadContents(ctx, gitOwner, gitRepo, templatePath, &github.RepositoryContentGetOptions{})
	if err != nil {
		return nil, err
	}
	if reader != nil {
		defer reader.Close()
	}

	if response == nil || response.Response == nil || response.StatusCode != 200 {
		status := "unknown status"
		if response != nil && response.Response != nil {
			status = response.Status
		}

		return nil, fmt.Errorf("unexpected GitHub response: %s", status)
	}

	content, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}

	return content, nil
}
